services:
  api:
    image: api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        - "8080:8080"
        - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ASPNETCORE_ConnectionStrings__WebApiDatabase=${ASPNETCORE_ConnectionStrings__WebApiDatabase}
      - ASPNETCORE_JWT__Secret=${ASPNETCORE_JWT__Secret}
      - ASPNETCORE_JWT__Lifetime=${ASPNETCORE_JWT__Lifetime}

  db:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
