name: Run Playwright Tests

on:
  # Trigger when there is a pull request to main or development branches
  pull_request:
    branches:
      - main
      - development
  # Trigger when there are pushes to main or development branches
  push:
    branches:
      - main
      - development
  # Manual trigger option in GitHub Actions
  workflow_dispatch:

jobs:
  runPlaywrightTests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'latest'

      - name: Build Frontend
        run: |
          cd frontend/
          npm install
          npm run build

      - name: Build PlaywrightTests
        run: |
          cd PlaywrightTests/
          dotnet build
          pwsh bin/Debug/net8.0/playwright.ps1 install

      - name: Run API and PlaywrightTests
        run: |
          # Start the API in the background
          cd api
          dotnet run 
          cd ../frontend
          npm run start
          &
          sleep 5
          # Switch to PlaywrightTests directory and run tests
          cd ../E2ETests/
          dotnet test
          # Kill the API process running on port 5000
          kill -9 $(lsof -t -i:5000)
        env:
          ASPNETCORE_ENVIRONMENT: Development
          ASPNETCORE_ConnectionStrings__WebApiDatabase: ${{ secrets.WEBAPIDATABASE }}
          ASPNETCORE_JWT__Secret: ${{ secrets.JWTSECRET }}
          ASPNETCORE_JWT__Lifetime: ${{ secrets.JWTLIFETIME }}
          ASPNETCORE_TestJwt: ${{ secrets.TEST_JWT }}
